project:
  type: book
  output-dir: docs
  
book:
  title: "Stat2"
  author: "math4mad"
  description: | 
    TBA
  #cover-image: images/cover.png
  site-url: https://math4mad.github.io/stat2-notes/
  repo-url: https://github.com/math4mad/stat2-notes
  repo-branch: main
  repo-actions: [edit]
  #sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: ./contents/my-first-book.qmd
      chapters: 
        - ./contents/hello-world.qmd
    - part: UnitA:LinearRegression
      chapters:
        - ./contents/chapter03/chapter03-1.qmd

  appendices:
    - ./contents/appendix-notes.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
    warning: false
